// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohvtqsjyvfctjapqpbtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9odnRxc2p5dmZjdGphcHFwYnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MjI0MzMsImV4cCI6MjA3NDI5ODQzM30.eFZ2PzJP_DUJ9v1bwByJeIpAeafsTOYcRPjU2w1g4Ic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});